version: '3.1'

networks:
  records:

services:
  users-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - user-storage:/var/lib/mysql

  hardware-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: hardware
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - hardware-storage:/var/lib/mysql

  records-db:
    image: influxdb:2.5.1
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root
      - DOCKER_INFLUXDB_INIT_ORG=at20057
      - DOCKER_INFLUXDB_INIT_BUCKET=hardware
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - records

volumes:
  user-storage:
  hardware-storage:
  influxdb-storage:
