version: '3.1'

networks:
  records:

services:
  users-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - user-storage:/var/lib/mysql

volumes:
  user-storage:
